"""SDWPF loaders, features, and training pipeline."""

from sdwpf.constants import (
    DEFAULT_METEO_MAX_LAG,
    ERA5_EXTRA_COLS,
    POOL_TURB_ID_COL,
    SDWPF_V1_ANCHOR,
    STEPS_PER_DAY,
    STEPS_PER_HOUR,
)
from sdwpf.data import (
    load_era5_for_turbine,
    load_one_turbine,
    merge_scada_era5,
    sanitize_scada_for_forecasting,
)
from sdwpf.features import (
    CALENDAR_FEATURE_COLS,
    add_features,
    build_feature_columns,
    resolve_horizon_steps,
    temporal_split,
    temporal_split_by_unique_datetime,
    temporal_split_train_val_test,
    temporal_split_train_val_test_by_unique_datetime,
    walk_forward_indices,
)
from sdwpf.paths import default_scada_csv_path, default_weather_csv_path, project_root
from sdwpf.pipeline import (
    XGB_DEVICE_ENV,
    SdwpfRunResult,
    build_modeling_frame,
    effective_xgb_device,
    evaluate_on_indices,
    resolve_xgb_device_spec,
    load_frame_for_run,
    maybe_log_mlflow,
    train_and_evaluate,
    train_and_evaluate_pooled,
    xgboost_built_with_cuda,
)

__all__ = [
    "DEFAULT_METEO_MAX_LAG",
    "POOL_TURB_ID_COL",
    "ERA5_EXTRA_COLS",
    "SDWPF_V1_ANCHOR",
    "STEPS_PER_DAY",
    "STEPS_PER_HOUR",
    "XGB_DEVICE_ENV",
    "SdwpfRunResult",
    "effective_xgb_device",
    "resolve_xgb_device_spec",
    "xgboost_built_with_cuda",
    "CALENDAR_FEATURE_COLS",
    "add_features",
    "build_feature_columns",
    "build_modeling_frame",
    "default_scada_csv_path",
    "default_weather_csv_path",
    "evaluate_on_indices",
    "load_era5_for_turbine",
    "load_frame_for_run",
    "load_one_turbine",
    "maybe_log_mlflow",
    "merge_scada_era5",
    "project_root",
    "resolve_horizon_steps",
    "sanitize_scada_for_forecasting",
    "temporal_split",
    "temporal_split_by_unique_datetime",
    "temporal_split_train_val_test",
    "temporal_split_train_val_test_by_unique_datetime",
    "train_and_evaluate",
    "train_and_evaluate_pooled",
    "walk_forward_indices",
]
